library(tidyverse)
library(maps)
library(ggthemes)
library(dplyr)
library(mapproj)
library(stringr)
library(DataExplorer)
library(rgdal)
library(lubridate)
library(GGally)
library(shiny)
library(shinydashboard)
source("UIred.R")
source("Serverred.R")

shinyApp(ui, server)